FROM base-py-cuda-10.2:latest as ai4e_base
#FROM mcr.microsoft.com/aiforearth/base-py:latest
RUN conda update conda
RUN apt-get update
RUN apt-get install gcc g++ git -y
# Note: supervisor.conf reflects the location and name of your api code.
# If the default (./my_api/runserver.py) is renamed, you must change supervisor.conf
# Copy your API code
COPY ./pytorch_api /app/pytorch_api/
COPY ./supervisord.conf /etc/supervisord.conf

RUN echo "source activate ai4e_py_api" >> ~/.bashrc \
    && conda env update --name ai4e_py_api --file /app/pytorch_api/app-environment-dev.yml 
# PIL will be installed with pytorch

# startup.sh is a helper script
COPY ./startup.sh /
RUN chmod +x /startup.sh

# Application Insights keys and trace configuration
ENV APPINSIGHTS_INSTRUMENTATIONKEY= \
    TRACE_SAMPLING_RATE=1.0

# The following variables will allow you to filter logs in AppInsights
ENV SERVICE_OWNER=AI4E_PyTorch_Example \
    SERVICE_CLUSTER=Local\ Docker \
    SERVICE_MODEL_NAME=AI4E_PyTorch_Example \
    SERVICE_MODEL_FRAMEWORK=Python \
    SERVICE_MODEL_FRAMEOWRK_VERSION=3.6.6 \
    SERVICE_MODEL_VERSION=1.0

ENV API_PREFIX=/v1/pytorch_api

# Expose the port that is to be used when calling your API
EXPOSE 80
HEALTHCHECK --interval=1m --timeout=3s --start-period=20s \
  CMD curl -f http://localhost/${API_PREFIX}/  || exit 1
ENTRYPOINT [ "/usr/local/envs/ai4e_py_api/bin/jupyter", "lab", "--notebook-dir", "/app", "--no-browser", "--ip=0.0.0.0", "--port=8888", "--allow-root" ]
