FROM base-py-cuda-10.1:latest as ai4e_base
#FROM mcr.microsoft.com/aiforearth/base-py:latest
RUN conda update conda
RUN apt-get update
RUN apt-get install gcc g++ git ffmpeg libsm6 libxext6 -y
# Note: supervisor.conf reflects the location and name of your api code.
# If the default (./my_api/runserver.py) is renamed, you must change supervisor.conf
# Copy your API code
COPY ./pytorch_api /app/pytorch_api/
COPY ./supervisord.conf /etc/supervisord.conf

RUN echo "source activate ai4e_py_api" >> ~/.bashrc \
    && conda env update --name ai4e_py_api --file /app/pytorch_api/app-environment-prod.yml 
# PIL will be installed with pytorch

# prebuilt det 2 wouldn't compile with gpu support, compiling to support all architectures following
# their dockerfile https://github.com/facebookresearch/detectron2/blob/master/docker/Dockerfile
# set FORCE_CUDA because during `docker build` cuda is not accessible
ENV FORCE_CUDA="1"
# This will by default build detectron2 for all common cuda architectures and take a lot more time,
# because inside `docker build`, there is no way to tell which architecture will be used.
ARG TORCH_CUDA_ARCH_LIST="Kepler;Kepler+Tesla;Maxwell;Maxwell+Tegra;Pascal;Volta;Turing"
ENV TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST}"
RUN git clone https://github.com/facebookresearch/detectron2.git detectron2_repo --branch v0.1.2 
RUN pip install --user -e detectron2_repo

# startup.sh is a helper script
COPY ./startup.sh /
RUN chmod +x /startup.sh

# Application Insights keys and trace configuration
ENV APPINSIGHTS_INSTRUMENTATIONKEY= \
    TRACE_SAMPLING_RATE=1.0

# The following variables will allow you to filter logs in AppInsights
ENV SERVICE_OWNER=AI4E_PyTorch_Example \
    SERVICE_CLUSTER=Local\ Docker \
    SERVICE_MODEL_NAME=AI4E_PyTorch_Example \
    SERVICE_MODEL_FRAMEWORK=Python \
    SERVICE_MODEL_FRAMEOWRK_VERSION=3.6.6 \
    SERVICE_MODEL_VERSION=1.0

ENV API_PREFIX=/v1/pytorch_api

# Expose the port that is to be used when calling your API
EXPOSE 80
HEALTHCHECK --interval=1m --timeout=3s --start-period=20s \
  CMD curl -f http://localhost/${API_PREFIX}/  || exit 1
ENTRYPOINT [ "/startup.sh" ]
